### ISSUE TITLE
ImportError: cannot import name '_endpoint_from_view_func' from 'flask.helpers' (/usr/local/lib/python3.9/dist-packages/flask/helpers.py)

### ISSUE THREAD

**Issue by norachiv12** [P0cL4bs/wifipumpkin3#117]
When i run wifipumpkin3 i get this issue.

ImportError: cannot import name '_endpoint_from_view_func' from 'flask.helpers' (/usr/local/lib/python3.9/dist-packages/flask/helpers.py)

**Comment by Arinerron** [comment]
why is this invalid? I am having the same issue

**Comment by 2020devanshu** [comment]
same issue with me too

**Comment by bmatticus** [comment]
I downgraded from flask 2.0.0 to flask 1.1.2 to fix this issue myself

**Comment by pamelars86** [comment]
It happens to me today!
and it was working fine yesterday! :o

**Comment by Pulixe** [comment]
Yes,  downgrade to Flask==1.1.2  and its works... 
also use python 3.8.7

**Comment by ElizabethCappon** [comment]
Downgrading to Flask 1.1.2 gives me the following error:

FileNotFoundError: [Errno 2] No such file or directory: '/home/user/anaconda3/lib/python3.8/site-packages/idna-2.10.dist-info/METADATA'

Any solutions for this? I'm stuck :(

**Comment by FoldedPanda** [comment]
Worked for me!  Just had to update requirements.txt for docker! :)

**Comment by illozzam** [comment]
Same problem here... I'll try to downgrade like the others.

**Comment by mh4x0f** [comment]
hi all, I'll add a patch to solve this coming soon. wait...

**Comment by mh4x0f** [comment]
news: in the last commit *branch dev)  i removed the support a API Rest because I not will support this feature anymore. I bump a new release with the version [here](https://github.com/P0cL4bs/wifipumpkin3/releases/tag/v1.0.8R2) , this solve the problem with flask version. 

obs:  please follow the guidelines on the website to install the wp3 on virtual env python it great and no error come from.

att, mh4x0f thanks for all 
happy hacking, have fun. hack the planet !

**Comment by flutterq** [comment]
[[Solved] cannot import name ‘_endpoint_from_view_func’ from ‘flask.helpers’ in python](https://exerror.com/solved-cannot-import-name-_endpoint_from_view_func-from-flask-helpers-in-python/)

**Comment by toddman2** [comment]
I get a problem with some package I cannot remember off the top because I had pinned the dreaded Werkzeug 0.16.1 version some time back.  That breaks my flask_restplus -- which I upgrade -- now only to hit this gem.  Public software isn't for the weak at heart.  It's a drag but not the end of the world.  I appreciate the author's time already.

Side note, I fixed my problem too by pinning the 1.1.2 Flask version to my requirements.txt file.
