### ISSUE TITLE
Runtime Error: PyQt5.sip not found, but it is installed.

### ISSUE THREAD

**Issue by protocol-AMG** [P0cL4bs/wifipumpkin3#17]
I'm running Kali-rolling 2020.1. When running wp3 the following error occurred.
<img width="738" alt="Screen Shot 2020-04-20 at 02 19 22" src="https://user-images.githubusercontent.com/54980498/79720208-19621480-82ae-11ea-8da1-0115347832e4.png">
However, the package is installed and the version meets requirement.
<img width="592" alt="Screen Shot 2020-04-20 at 02 17 50" src="https://user-images.githubusercontent.com/54980498/79720282-3c8cc400-82ae-11ea-8900-cfe997ee7913.png">
Any idea?

**Comment by mh4x0f** [comment]
**I am going to answer because this problem will be researched a lot here, but you should follow the issue template. This is really important!**

this problem only to be solve if you uninstall the PyQt5, because the **PyQt5  5.14.1** is broken.
``` sh
pip3 uninstall PyQt5==5.14.1
pip3 uninstall PyQt5-sip==12.7.2
``` 
You can to install a version of PyQt5 that working fine on resp. follow the steps:
``` sh
sudo apt-get update -y
sudo apt-get install -y python3-pyqt5
python3 --version
```
now, with PyQt5 installed on system only to check if everything ok:
``` sh
python3 -c "from PyQt5.QtCore import QSettings; print('done')"
```
 if you got the message `done`, nice. the next step is **remove somes lines** from file **requirements.txt** on root the wifipumpkin3 project. Open the file and delete this lines:
``` 
PyQt5==5.14
PyQt5-sip==12.7.2
```
great, now  you can install the tool:
``` sh
python3 setup.py install 
```
> Finished processing dependencies for wifipumpkin3==1.0.0
done, if you got here, execute the tool with:
```
sudo wifipumpkin3
```
send me the feedback!

**Comment by protocol-AMG** [comment]
It was all good before `python3 setup.py install`. Running this command resulted in an error saying `/usr/local/lib/python3.8/dist-packages/` folder does not exist. 
I do have python3.8 installed but the `/usr/local/lib/python3.8/` folder was not there. 
I simply created `/usr/local/lib/python3.8/dist-packages/` and the problem was then solved.
wifipumpkin3 installed successfully for me.
Thank you!

**Comment by jezima** [comment]
everything was okay until i ran: python3 -c "from PyQt5.QtCore import QSettings; print('done')"
it didnt say done

**Comment by mh4x0f** [comment]
@protocol-AMG thank's for report this bug, after a lot of research, I managed to solve the problem seemingly.

**Comment by Thomas-Clauzel** [comment]
thanks, this post helped me too
