### ISSUE TITLE
Issue with self.udp_server

### ISSUE THREAD

**Issue by BreadV2** [P0cL4bs/wifipumpkin3#68]
**Description of the bug or feature request**
- When attempting to use command "start" it comes up with "AttributeError: 'Thread' object has no attribute 'isAlive'"

**Expected behavior**
- Expected to start the AccessPoint

**Screenshots**
Attached.
![Screenshot 2020-08-08 20:32:54](https://user-images.githubusercontent.com/69393014/89713005-92bb6b00-d962-11ea-977a-a62b5d3e4b7f.png)

**Desktop (please complete the following information):**
* Wifipumpkin3 1.0.7
* Virtual Machine (yes or no and which): No
* Operating System: Kali Linux
* version: 2020.2

**Comment by mh4x0f** [comment]
which the version of python you are using ? 
run:
python3 --version

**Comment by BreadV2** [comment]
Sorry, I forgot to include that in. Python is 3.8.5

**Comment by mh4x0f** [comment]
I found the problem, the python 3.8.5 change the function **isAlive** to *is_alive*. 

`Once the thread’s activity is started, the thread is considered ‘alive’. It stops being alive when its run() method terminates – either normally, or by raising an unhandled exception. The is_alive() method tests whether the thread is alive.`
font : [doc python ](https://docs.python.org/3/library/threading.html)

I will do something to solve this, because I support anothers versions the python.

**Comment by tirkarthi** [comment]
I have created https://github.com/P0cL4bs/wifipumpkin3/pull/79 . `is_alive` should be present in both python 2.7 and python 3.

**Comment by mh4x0f** [comment]
@BreadV2 thanks for report the issue.
