### ISSUE TITLE
Log Files

### ISSUE THREAD

**Issue by nokiaman2002** [P0cL4bs/wifipumpkin3#91]
captiveportal.log  pumpkin_proxy.log  pydns_server.log  responder3.log  sniffkin3.log

All the above are all 0 bytes. Is there any way of logging all traffic through the AP? Or making it more specific to capture particular creds?

I have left it all at default with pumpkinproxy=true.

Running: Kali 2020.3

**Comment by mh4x0f** [comment]
https://wifipumpkin3.github.io/docs/configuration/configuration-file

**Comment by nokiaman2002** [comment]
I have seen that and indeed I have been into the home directory, viewed hidden files and folders, found .config and there is no wifipumpkin directory there. In the wifipumpkin install directory there is the folder structure as laid out in the documentation and in the logs folder there is an ap folders and threads.log. In the ap folder there are six .log files all at 0 bytes even though I have run WP3 several times.
![wp3 jpeg](https://user-images.githubusercontent.com/30255400/93639962-b659e280-f9f1-11ea-89a5-68ff3403a352.jpg)

**Comment by s267554** [comment]
Check the log path in the output of `wp3 > info pumpkinproxy` under `Logger` section or whatever proxy/plugins you have used.
Brief description of wp3 `info` command [here](https://wifipumpkin3.github.io/docs/getting-started#core-commands)

You sure about running wifipumpkin3 as your current user instead of, let's say, "root" , by typing `sudo wifipumpkin3`? In that case you'll find a similar directory structure at `/root/.config/wifipumpkin3`
